name: Pub/Sub Trigger for GitHub Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Pub/Sub Trigger
        uses: google-github-actions/pubsub-trigger@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          subscription: ${{ vars.GCP_SUBSCRIPTION }}

      - name: Trigger GitHub Pipeline
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'my-pipeline.yml',
              ref: 'main'
            })